-- PokemonLean: Formal verification of the Pokémon Trading Card Game
-- This module serves as the root of the `PokemonLean` library.
-- Import modules here that should be built as part of the library.

-- === main-branch flat modules ===
import PokemonLean.Basic
import PokemonLean.Cards
import PokemonLean.Corpus
import PokemonLean.Solver
import PokemonLean.GameTheory
import PokemonLean.Semantics
import PokemonLean.BoardState
import PokemonLean.DamageCounters
import PokemonLean.Matchup
import PokemonLean.TrainerSystem
import PokemonLean.DeckBuilding
import PokemonLean.ACESpec
import PokemonLean.Win
import PokemonLean.Planner
import PokemonLean.Switching
import PokemonLean.Rotation
import PokemonLean.Format
import PokemonLean.Abilities
import PokemonLean.Decks
import PokemonLean.Prizes
import PokemonLean.StatusEffects
import PokemonLean.TypeChart
import PokemonLean.EnergyManagement
import PokemonLean.EnergyAcceleration
import PokemonLean.Replay
import PokemonLean.Stadium
import PokemonLean.LostZone
import PokemonLean.LostZoneThresholds
import PokemonLean.LostZoneBox
import PokemonLean.LostZoneCombos
import PokemonLean.TournamentRules
import PokemonLean.HandManagement
import PokemonLean.Archetypes
import PokemonLean.ArchetypeMatchups
import PokemonLean.RetreatMechanics
import PokemonLean.HandDisruption
import PokemonLean.PrizeDenial
import PokemonLean.TurnStructure
import PokemonLean.DeckConstraints
import PokemonLean.GXAttacks

-- === master-branch Core.* modules ===
import PokemonLean.Core.Types
import PokemonLean.Core.Card
import PokemonLean.Core.GameState
import PokemonLean.Core.DamageCalc
import PokemonLean.Core.Evolution
import PokemonLean.Core.SpecialConditions
import PokemonLean.Core.WinCondition
import PokemonLean.Core.RuleBox
import PokemonLean.Core.Trainers
import PokemonLean.Core.EnergySystem
import PokemonLean.Core.Retreat
import PokemonLean.Core.Setup
import PokemonLean.Core.TurnLoop
import PokemonLean.Core.AttackResolution
import PokemonLean.Core.GameLoop
import PokemonLean.Core.Solver
import PokemonLean.Core.DeckChecker
import PokemonLean.Core.PrizeTrade
import PokemonLean.Core.Interaction
import PokemonLean.Core.BattleStyles
import PokemonLean.Core.Paradox
import PokemonLean.Core.CoinFlip
import PokemonLean.Core.AbilityTiming
import PokemonLean.Core.Tournament
import PokemonLean.Core.FormatChecker
import PokemonLean.Core.CardDatabase
import PokemonLean.Core.Abilities
import PokemonLean.Core.SpecialMechanics
import PokemonLean.Core.Strategy
import PokemonLean.Core.Pocket
import PokemonLean.Core.PocketBattle
import PokemonLean.Core.LiveFormat
import PokemonLean.Core.Metagame
import PokemonLean.Core.SideDeck
import PokemonLean.Core.HistoricalFormats
import PokemonLean.Core.LostZoneDeck
import PokemonLean.Core.CharizardDeck
import PokemonLean.Core.ControlDeck
import PokemonLean.Core.ScarletViolet
import PokemonLean.Core.RulingEdgeCases
import PokemonLean.Core.EnergySystemDeep
import PokemonLean.Core.AbilityInteraction
import PokemonLean.Core.ItemAndTool
import PokemonLean.Core.BenchMechanics
import PokemonLean.Core.MatchupAnalysis
import PokemonLean.Core.ResourceManagement
import PokemonLean.Core.TurnStructure
import PokemonLean.Core.StadiumCards
import PokemonLean.Core.SupporterCards
import PokemonLean.Core.PrizeMapping
import PokemonLean.Core.Rotation
import PokemonLean.Core.MulliganSetup
import PokemonLean.Core.AttackCost
