-- This module serves as the root of the `PokemonLean` library.
-- Import modules here that should be built as part of the library.
import PokemonLean.Basic
import PokemonLean.Cards
import PokemonLean.Corpus
import PokemonLean.Solver
import PokemonLean.GameTheory
import PokemonLean.Semantics
import PokemonLean.BoardState
import PokemonLean.DamageCounters
import PokemonLean.Matchup
import PokemonLean.CardPool
import PokemonLean.AbilitySystem
import PokemonLean.PrizeCards
import PokemonLean.TrainerSystem
import PokemonLean.Deck
import PokemonLean.DeckBuilding
import PokemonLean.ACESpec
import PokemonLean.Win
import PokemonLean.Planner
import PokemonLean.Switching
import PokemonLean.Rotation
import PokemonLean.Format
import PokemonLean.Abilities
import PokemonLean.TrainerCards
import PokemonLean.Decks
import PokemonLean.Prizes
import PokemonLean.Tournament
import PokemonLean.MixedStrategy
import PokemonLean.Evolution
import PokemonLean.VSTAR
import PokemonLean.StatusEffects
import PokemonLean.TypeChart
import PokemonLean.EnergyManagement
import PokemonLean.EnergyAcceleration
import PokemonLean.Mulligan
import PokemonLean.Replay
import PokemonLean.Stadium
import PokemonLean.SpecialConditions
import PokemonLean.LostZone
import PokemonLean.LostZoneThresholds
import PokemonLean.LostZoneBox
import PokemonLean.LostZoneCombos
import PokemonLean.TournamentRules
import PokemonLean.HandManagement
import PokemonLean.AncientTrait
